faren = float(input("Ingresa los grados Farenheit "))
pesos = float(input("Ingresa la cantidad de pesos "))
celsius= ((faren-32)*5/9)
dolares = (pesos*20.3)
print("La conversion de los grados farenheits {} a Celsius son: {}".format(faren, celsius))
print("La conversión de pesos {} a dolares es: {}".format(pesos, dolares))